const books = [
    { id: 1, title: "The Name of the Wind", author: "Patrick Rothfuss", genre: "Fantasy" },
    { id: 2, title: "Dune", author: "Frank Herbert", genre: "Science Fiction" },
    { id: 3, title: "1984", author: "George Orwell", genre: "Dystopian" },
    { id: 4, title: "The Da Vinci Code", author: "Dan Brown", genre: "Action & Adventure" },
    { id: 5, title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", genre: "Mystery" },
    { id: 6, title: "It", author: "Stephen King", genre: "Horror" },
    { id: 7, title: "Gone Girl", author: "Gillian Flynn", genre: "Thriller & Suspense" },
    { id: 8, title: "The Book Thief", author: "Markus Zusak", genre: "Historical Fiction" },
    { id: 9, title: "Pride and Prejudice", author: "Jane Austen", genre: "Romance" },
    { id: 10, title: "Normal People", author: "Sally Rooney", genre: "Contemporary Fiction" },
    { id: 11, title: "Beloved", author: "Toni Morrison", genre: "Literary Fiction" },
    { id: 12, title: "One Hundred Years of Solitude", author: "Gabriel García Márquez", genre: "Magical Realism" },
    { id: 13, title: "Maus", author: "Art Spiegelman", genre: "Graphic Novel" },
    { id: 14, title: "Tenth of December", author: "George Saunders", genre: "Short Story" },
    { id: 15, title: "The Hunger Games", author: "Suzanne Collins", genre: "Young Adult" },
    { id: 16, title: "Charlotte's Web", author: "E.B. White", genre: "Children's" },
    { id: 17, title: "Becoming", author: "Michelle Obama", genre: "Memoir & Autobiography" },
    { id: 18, title: "Steve Jobs", author: "Walter Isaacson", genre: "Biography" },
    { id: 19, title: "Kitchen Confidential", author: "Anthony Bourdain", genre: "Food & Drink" },
    { id: 20, title: "Humans of New York", author: "Brandon Stanton", genre: "Art & Photography" },
    { id: 21, title: "Atomic Habits", author: "James Clear", genre: "Self-Help" },
    { id: 22, title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", genre: "History" },
    { id: 23, title: "Into the Wild", author: "Jon Krakauer", genre: "Travel" },
    { id: 24, title: "In Cold Blood", author: "Truman Capote", genre: "True Crime" },
    { id: 25, title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", genre: "Humor" },
    { id: 26, title: "The Year of Magical Thinking", author: "Joan Didion", genre: "Essays" },
    { id: 27, title: "The Life-Changing Magic of Tidying Up", author: "Marie Kondo", genre: "Guide/How-To" },
    { id: 28, title: "The Power of Now", author: "Eckhart Tolle", genre: "Religion & Spirituality" },
    { id: 29, title: "Guns, Germs, and Steel", author: "Jared Diamond", genre: "Humanities & Social Sciences" },
    { id: 30, title: "The Whole-Brain Child", author: "Daniel J. Siegel", genre: "Parenting & Families" },
    { id: 31, title: "The Gene: An Intimate History", author: "Siddhartha Mukherjee", genre: "Science & Technology" },
    { id: 32, title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", genre: "Children's Nonfiction" }
]

export { books }